spring:
  datasource:
    url: jdbc:mysql://localhost:3306/glxy?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: spring-security

  redis:
    host: 192.168.31.113
    port: 6379   #默认端口号
    password: 123456
    database: 0 #默认提供了16个数据库（可以在配置文件中改） 默认操作0号数据库，可以在命令行 select 1 选择1号数据库，
    timeout: 1800000
    jedis:
      #Redis连接池配置
      pool:
        max-active: 20 #最大链接数
        max-wait: -1 #连接池最大阻塞等待时间
        max-idle: 5   #连接池的最大空闲连接
        min-idle: 0   #连接池的最小空闲连接

logging:
  level:
    root: info #设置日志级别
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
