server:
  port: 8080
  servlet:
    context-path: /myboot

#  @ConfigurationProperties(prefix = "school")   赋值
school:
  name: 百度
  website: www.baidu.com
  address: 南京的大学区

site: www.baidu.com
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://api.lemonban.com:3306/test
    username: future
    password: 123456